const events = [
        {
            id: 1,
            name: "Halloween Costume Party",
            date: "2024-10-31",
            location: "Downtown Club",
            description: "Join us for a spooky night filled with fun, music, and prizes for the best costumes!",
            image: "/images/valent.jpeg",
        },
        {
            id: 2,
            name: "New Year's Eve Bash",
            date: "2024-12-31",
            location: "Sky Lounge",
            description: "Ring in the New Year with a glamorous party featuring live music and fireworks!",
            image: "/images/yoga.jpeg",
        },
        {
            id: 3,
            name: "Summer Pool Party",
            date: "2024-07-15",
            location: "Luxury Resort",
            description: "Dive into summer with our epic pool party! Enjoy drinks, games, and DJ performances.",
            image: "/images/pool.jpg",
        },
        {
            id: 4,
            name: "Valentine's Day Dance",
            date: "2024-02-14",
            location: "Romantic Hall",
            description: "Celebrate love with a romantic evening of dancing, dining, and delightful surprises.",
            image: "/images/valent.jpeg",
        },
        {
            id: 5,
            name: "St. Patrick's Day Celebration",
            date: "2024-03-17",
            location: "Irish Pub",
            description: "Join us for a night of Irish music, dancing, and green beer to celebrate St. Patrick's Day!",
            image: "/images/pat.jpeg",
        },
        {
            id: 6,
            name: "Beach Bonfire Party",
            date: "2024-06-20",
            location: "Sunset Beach",
            description: "Enjoy a night under the stars with a bonfire, s'mores, and acoustic music by the beach.",
            image: "/images/bonfire.jpeg",
        },
        {
            id: 7,
            name: "Masquerade Ball",
            date: "2024-11-15",
            location: "Grand Ballroom",
            description: "Put on your mask and join us for an elegant evening of mystery and dance.",
            image: "/images/mas.jpeg",
        },
        {
            id: 8,
            name: "Wine Tasting Gala",
            date: "2024-09-10",
            location: "Vineyard Estate",
            description: "Savor exquisite wines paired with gourmet food at our exclusive wine tasting event.",
            image: "/images/wine.jpeg",
        },
        {
            id: 9,
            name: "Retro Dance Party",
            date: "2024-05-05",
            location: "Old School Hall",
            description: "Travel back in time with us for a night of disco, funk, and all your favorite retro hits!",
            image: "/images/retro.jpeg",
        },
        {
            id: 10,
            name: "Outdoor Music Festival",
            date: "2024-08-20",
            location: "City Park",
            description: "Join us for a day of live music, food trucks, and fun activities for all ages!",
            image: "/images/outdoor.jpeg",
        },
        {
            id: 11,
            name: "Spring Art Fair",
            date: "2024-04-10",
            location: "Art Gallery",
            description: "Explore local artists and their works at our vibrant spring art fair. Enjoy live music and refreshments!",
            image: "/images/spring.jpeg",
        },
        {
            id: 12,
            name: "Food Truck Festival",
            date: "2024-05-25",
            location: "Downtown Square",
            description: "Taste a variety of cuisines from the best food trucks in the city at our annual food truck festival!",
            image: "/images/food.jpeg",
        },
        {
            id: 13,
            name: "Tech Conference 2024",
            date: "2024-09-15",
            location: "Convention Center",
            description: "Join industry leaders for discussions on the latest trends in technology, networking opportunities, and workshops.",
            image: "/images/tech.jpeg",
        },
        {
            id: 14,
            name: "Charity Run",
            date: "2024-11-01",
            location: "City Stadium",
            description: "Participate in our charity run to raise funds for local charities. All ages are welcome!",
            image: "/images/run.jpeg",
        },
        {
            id: 15,
            name: "Christmas Market",
            date: "2024-12-05",
            location: "Town Square",
            description: "Get into the holiday spirit at our Christmas market featuring local vendors, crafts, and festive treats!",
            image: "/images/christ.jpeg",
        },
        {
            id: 16,
            name: "Yoga in the Park",
            date: "2024-06-10",
            location: "Central Park",
            description: "Relax and rejuvenate with a morning yoga session in the park. All skill levels are welcome!",
            image: "/images/yoga.jpeg",
        },
        {
            id: 17,
            name: "Movie Night Under the Stars",
            date: "2024-07-30",
            location: "Community Field",
            description: "Enjoy a classic movie screening outdoors with popcorn and blankets. Bring your friends and family!",
            image: "/images/moviie.jpeg",
        },
        {
            id: 18,
            name: "Karaoke Night",
            date: "2024-08-12",
            location: "Local Pub",
            description: "Show off your singing skills at our fun karaoke night! Prizes for the best performances!",
            image: "/images/kara.jpeg",
        },
        {
            id: 19,
            name: "Nature Walk",
            date: "2024-10-10",
            location: "Nature Reserve",
            description: "Join us for a guided nature walk and discover the beauty of our local flora and fauna.",
            image: "/images/nature.jpeg",
        },
        {
            id: 20,
            name: "Craft Beer Festival",
            date: "2024-09-25",
            location: "Brewery Grounds",
            description: "Sample a variety of craft beers from local breweries and enjoy live music and food pairings!",
            image: "/images/pat.jpeg",
        }
  ];
  
  export default events;
  